max_width = 120
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Max"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
# overflow_delimited_expr = true
# struct_field_align_threshold = 4
# enum_discrim_align_threshold = 4
edition = "2018"
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
# condense_wildcard_suffixes = true
# unstable_features = false
